#! perl

use strict;
use warnings;

use TAP::Harness;
use File::Find;

my @tfiles;
find(sub { /\.t$/ && push @tfiles, $File::Find::name; }, "t");

my %harness_options = (
  exec      => \&which_command,
  verbosity => 0,
  jobs      => 1,
  );

TAP::Harness->new( \%harness_options )->runtests(sort @tfiles);

sub which_command {
  my $tap = shift;
  my $file = shift;

  return [qw(./parrot/parrot -w -I ./src/parrot/ -L ./src/pmc),
    $file];
}
